quarkus.log.level=INFO
quarkus.http.port=8080

# mail server configuration
mail.hostname=localhost
mail.port=9000
mail.from=mailer@mail.com

quarkus.datasource.db-kind=h2
quarkus.datasource.username=
quarkus.datasource.password=
quarkus.hibernate-orm.dialect=org.hibernate.dialect.H2Dialect
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.datasource.jdbc.url=jdbc:h2:mem:person
quarkus.hibernate-orm.log.sql=false
quarkus.hibernate-orm.sql-load-script=data.sql

quarkus.hibernate-orm.dev-ui.allow-hql=true

%mysql.quarkus.datasource.db-kind=mysql
%mysql.quarkus.datasource.username=root
%mysql.quarkus.datasource.password=mysqladmin
%mysql.quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/person
%mysql.quarkus.hibernate-orm.log.sql=false
%mysql.quarkus.hibernate-orm.validate-in-dev-mode=false